### ISSUE TITLE
数据库脚本呢？

### ISSUE THREAD

**Issue by EagleSmith** [wang371758198/NFine.Framework.Core#1]
找不到数据库脚本，跑不走demo

**Comment by KillingMeNow** [comment]
> 找不到数据库脚本，跑不走demo

用命令建库 Add-Migration,Update-Database

**Comment by Dysheng** [comment]
update-database 后，数据库是空的啊

**Comment by Dysheng** [comment]
能否用mysql 呢？

**Comment by KillingMeNow** [comment]
> 能否用mysql 呢？

能用 我试过了

**Comment by xiaozhe** [comment]
你好，能提供数据库脚本吗？或者怎么用哪个命令？谢谢。

**Comment by EagleSmith** [comment]
nuget 命令行里执行Update-Database，项目是data那个
